# Generated by Django 3.1.1 on 2020-09-15 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200916_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='no_childeren',
            new_name='no_children',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 2, 29, 23, 933191)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 2, 29, 23, 932160)),
        ),
    ]
