# Generated by Django 3.1.1 on 2020-09-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200919_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_picture',
        ),
    ]
