# Generated by Django 3.1.1 on 2020-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_customer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_picture',
            field=models.ImageField(null=True, upload_to='customer'),
        ),
    ]
