# Generated by Django 3.1.1 on 2020-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_customer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_picture',
            field=models.ImageField(null=True, upload_to='customer/'),
        ),
    ]
