# Generated by Django 3.1.1 on 2020-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200923_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_picture',
            field=models.ImageField(null=True, upload_to='customer'),
        ),
    ]
