# Generated by Django 3.1.1 on 2020-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200923_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer/'),
        ),
    ]
