# Generated by Django 3.1.1 on 2020-09-28 16:36

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20200929_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_picture',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.content_file_name),
        ),
    ]
