# Generated by Django 3.1.1 on 2020-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200929_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='no_children',
            field=models.IntegerField(default=0),
        ),
    ]
