# Generated by Django 3.1.1 on 2020-09-16 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('director_firstname', models.CharField(max_length=150)),
                ('director_lastname', models.CharField(max_length=150)),
                ('release_date', models.DateField(default=datetime.datetime(2020, 9, 16, 13, 59, 21, 311699))),
                ('cast', models.CharField(max_length=255)),
                ('num_of_items', models.IntegerField()),
                ('price', models.FloatField()),
                ('dvd_cover1', models.FileField(upload_to='')),
                ('dvd_cover2', models.FileField(upload_to='')),
                ('dvd_cover3', models.FileField(upload_to='')),
                ('date_registered', models.DateField(default=datetime.datetime(2020, 9, 16, 13, 59, 21, 311699))),
            ],
            options={
                'db_table': 'DVD',
            },
        ),
    ]
