# Generated by Django 3.1.1 on 2020-09-16 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='dvd_cover1',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='dvd_cover2',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='dvd_cover3',
        ),
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
