# Generated by Django 3.1.1 on 2020-09-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0003_auto_20200916_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvd',
            old_name='num_of_items',
            new_name='quantity',
        ),
    ]
