# Generated by Django 3.1.1 on 2020-09-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0006_auto_20200917_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='dvd_cover1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dvd',
            name='dvd_cover2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dvd',
            name='dvd_cover3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='release_date',
            field=models.DateField(),
        ),
    ]
