# Generated by Django 3.1.1 on 2020-09-17 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0010_auto_20200917_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 14, 56, 55, 747387)),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='dvd_cover1',
            field=models.ImageField(null=True, upload_to='dvd'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='dvd_cover2',
            field=models.ImageField(null=True, upload_to='dvd'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='dvd_cover3',
            field=models.ImageField(null=True, upload_to='dvd'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 14, 56, 55, 747387)),
        ),
    ]
