# Generated by Django 3.1.1 on 2020-09-19 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0012_auto_20200919_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='cast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 17, 4, 29, 963872)),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 17, 4, 29, 963872)),
        ),
    ]
