# Generated by Django 3.1.1 on 2020-09-19 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0014_auto_20200919_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='cast',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 17, 15, 43, 554277)),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 17, 15, 43, 554277)),
        ),
    ]
