# Generated by Django 3.1.1 on 2020-10-09 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0018_auto_20200923_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 15, 34, 16, 392992)),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 15, 34, 16, 392992)),
        ),
    ]
