# Generated by Django 3.1.1 on 2020-10-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('items_ordered', models.IntegerField()),
                ('total_price', models.FloatField()),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
